# Generated by Django 2.1.7 on 2019-03-30 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paste_text', models.TextField(blank=True, null=True)),
                ('paste_created', models.DateTimeField(verbose_name='date paste created')),
                ('paste_modified', models.DateTimeField(verbose_name='date paste modified')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_created', models.DateTimeField(verbose_name='date user created')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasteCloudApp.User'),
        ),
    ]
