# Generated by Django 2.1.7 on 2019-04-20 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasteCloudApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('paste_id', models.IntegerField(primary_key=True, serialize=False)),
                ('paste_name', models.CharField(max_length=200)),
                ('paste_text', models.TextField(blank=True, null=True)),
                ('paste_created', models.DateTimeField(verbose_name='date paste created')),
                ('paste_modified', models.DateTimeField(verbose_name='date paste modified')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasteCloudApp.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
