# Generated by Django 2.1.7 on 2019-04-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasteCloudApp', '0002_auto_20190420_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paste',
            old_name='paste_name',
            new_name='paste_title',
        ),
        migrations.AddField(
            model_name='paste',
            name='paste_username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
