# Generated by Django 2.1.7 on 2019-04-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasteCloudApp', '0003_auto_20190420_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='paste_created',
            field=models.DateTimeField(auto_now=True, verbose_name='date paste created'),
        ),
        migrations.AlterField(
            model_name='paste',
            name='paste_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paste',
            name='paste_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='date paste modified'),
        ),
    ]
